### ISSUE TITLE
v1.0.0b1 not available on the win-32 platform

### ISSUE THREAD

**Issue by spencerkclark** [conda-forge/cftime-feedstock#2]
`cftime` was recently updated to version 1.0.0b1.  The updates have appeared on conda-forge for all platforms except win-32, which is still on version 1.0.0a3: https://anaconda.org/conda-forge/cftime.  Did something go wrong in the updating process?

**Comment by jhamman** [comment]
@ocefpaf - any ideas?

**Comment by msarahan** [comment]
Conda-forge no longer supports win-32.  No new builds will include win-32.  I can't find any sort of official announcement, but I know the decision was made.  Try asking on the gitter channel if you need more explanation.

**Comment by jhamman** [comment]
Thanks @msarahan. ping @shoyer.

**Comment by shoyer** [comment]
OK, fair enough.

But can we remove the out-dated `1.0.0a3` version from conda-forge? I don't think we want win-32 users to inadvertently update to these prerelease versions.

**Comment by ocefpaf** [comment]
> But can we remove the out-dated `1.0.0a3` version from conda-forge?

Done.
